
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Signal Messenger notify platform (Signal REST API must be reachable from HA)
notify:
  - name: signal
    platform: signal_messenger
    url: "http://127.0.0.1:8080" # URL where the Signal Messenger REST API is listening
    number: "+4915120204977"     # sender number (Signal account)
    recipients:                  # one or more default recipients
      - "group.b0xsNGFGR1Fva1Y0cklCWk56d2tnUytYbmg5eEExcXNjNmtNK2cxRm1uWT0="

rest_command:
  signal_send:
    url: "http://127.0.0.1:8080/v2/send"
    method: POST
    headers:
      Content-Type: application/json
    payload: >
      {
        "message": "{{ message }}",
        "number": "{{ number }}",
        "recipients": {{ recipients | tojson }}
      }
  anarchist_homepage:
    url: "https://www.anarchistquotes.com/"
    method: GET
    headers:
      User-Agent: "Mozilla/5.0 (Home Assistant)"
  anarchist_quote:
    url: "{{ quote_url }}"
    method: GET
    headers:
      User-Agent: "Mozilla/5.0 (Home Assistant)"
  wikiquote:
    url: "https://en.wikiquote.org/w/api.php?action=parse&page={{ author }}&prop=wikitext&format=json&redirects=1"
    method: GET
    headers:
      User-Agent: "Mozilla/5.0 (Home Assistant)"
  jungewelt_gerhard_hanloser:
    url: "https://www.jungewelt.de/autor/512"
    method: GET
    headers:
      User-Agent: "Mozilla/5.0 (Home Assistant)"


automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml